### ISSUE TITLE
issue showing only first frame

### ISSUE THREAD

**Issue by ronak248** [itsmeichigo/ICGVideoTrimmer#1]
hi

thanks for code. but after selecting video its showing only one first  frame static.please reply asap

**Comment by itsmeichigo** [comment]
Please explain further your issue or I wouldn't be able to help.

Thanks.

**Comment by itsmeichigo** [comment]
Fixed in [commit 40](https://github.com/itsmeichigo/ICGVideoTrimmer/commit/bf372bc745a4aaed52e36112e4a8cf5f9fe2fb23).

**Comment by nlabhart** [comment]
@itsmeichigo what was the issue here? I'm seeing the same thing when doing this. I'm using Swift, let me know if thats a problem.

**Comment by itsmeichigo** [comment]
Hi, using Swift shouldn't be a problem. It'd be great if you raise a question (with detailed descriptions of the issue you're encountering) on StackOverflow first, so others can help you.

**Comment by nlabhart** [comment]
Ok, I will do that. However, this issue is directly related to the problem I was having. And is described by @ronak248 in the first post. I'm only seeing the first frame.

**Comment by nlabhart** [comment]
Also, @itsmeichigo, will this work without storyboards? Your example uses a storyboard, and works perfectly. Mine does not, and has these problems.
