### ISSUE TITLE
How can I export timing VIDEO to disk not Album?

### ISSUE THREAD

**Issue by poholo** [itsmeichigo/ICGVideoTrimmer#14]
How can I export timing VIDEO to disk not Album?

**Comment by thy3331** [comment]
you might want to di it yourself,using AVAssetExportSession to export your video to your disk,set AVAssetExportSession's outputURL to define where your fils should exported,you may also want to check this out, a modified exportSession from AVAssetExportSession

Here is the link:👇
 https://github.com/rs/SDAVAssetExportSession

**Comment by poholo** [comment]
thanks
