### ISSUE TITLE
load frame slow

### ISSUE THREAD

**Issue by qlj2009** [itsmeichigo/ICGVideoTrimmer#2]
I have solved the problem only displays the first frame, but if the video is not compressed, and a long time would be very slow to load frame, recommend using UITableView lazy load each frame

**Comment by itsmeichigo** [comment]
Hi, thanks for the suggestion. I'll take a look at this issue and see what I can do.

**Comment by qlj2009** [comment]
3 minutes..

**Comment by itsmeichigo** [comment]
In your case is there any image loaded to the trimmer view? I suppose they are fully loaded but the scrolling is slow?

**Comment by qlj2009** [comment]
Uncompressed and long video, it takes time to get all the images in addFrames method
原始邮件
发件人:Huong Donotifications@github.com
收件人:itsmeichigo/ICGVideoTrimmerICGVideoTrimmer@noreply.github.com
抄送:JerryQiuqlj2009@gmail.com
发送时间:2015年3月4日(周三) 11:47
主题:Re: [ICGVideoTrimmer] load frame slow (#2)


In your case is there any image loaded to the trimmer view? I suppose they are fully loaded but the scrolling is slow?

**Comment by itsmeichigo** [comment]
Fixed in [commit 43].(https://github.com/itsmeichigo/ICGVideoTrimmer/commit/32d955784ac54367addb00653098550c30b6f1c8)
