### ISSUE TITLE
I found a bug..

### ISSUE THREAD

**Issue by donobono** [itsmeichigo/ICGVideoTrimmer#20]
Thank you for sharing great sources!!
I found a bug so I report it..

If user selects a video which is shorter than _minLength, rightOverlayView moved weird.. 
Please fix it.. I tried to fix, but too complicated for me..

**Comment by itsmeichigo** [comment]
Hi, thanks for dropping by. 

The idea about setting `minLength` is that you make sure user can't select a shorter video than required. It'd be better that you do a check in your app to make sure that user only needs to trim their video if its duration is longer than minimum length. That makes sense right?
