### ISSUE TITLE
In iOS 10, when playing, audio is fine, but the video is black. Working fine in iOS 9.

### ISSUE THREAD

**Issue by BJGanesh** [itsmeichigo/ICGVideoTrimmer#22]
The video layer is black, but the audio is playing. This issue is visible only in iOS 10. Below versions are working fine. Even the observeValueForKeyPath status returns AVPlayerStatusReadyToPlay, but the video somehow is not rendering.

**Comment by iOSDevil** [comment]
self.playerLayer.frame = self.videoLayer.layer.frame;

**Comment by BJGanesh** [comment]
Yeah! Thanks. I have solved it.
