### ISSUE TITLE
Get video size when the slider changes

### ISSUE THREAD

**Issue by dipen0807** [itsmeichigo/ICGVideoTrimmer#23]
How to get video's size when I change the slider, please suggest, any little help would be a great relief.

**Comment by itsmeichigo** [comment]
Can you elaborate your question? I can't help if I don't understand it :]

**Comment by dipen0807** [comment]
I wanna implement a functionality which lets user to upload a video having maximum size of 25 MB. So as the range slider of video changes, there will be a label which will show the video size for selected region.

**Comment by itsmeichigo** [comment]
Sorry for not answering earlier. Normally you could get the size of the original video (e.g from NSFileManager or from the video you just recorded); then from the length of the chosen part of the video, you can compare with the total length to get the percentage of it. This percentage can be used to roughly calculate the size of the trimmed video. 

Hope this helps.
