### ISSUE TITLE
trackerColor assign or strong?

### ISSUE THREAD

**Issue by nihilenz** [itsmeichigo/ICGVideoTrimmer#25]
Hi,
just a question, why the `trackerColor` property is not `strong` in ICGVideoTrimmerView.h?
I got crash reports for ICGVideoTrimmerView.m line 129
`self.trackerView.backgroundColor = self.trackerColor ? self.trackerColor : [UIColor whiteColor];`
Am I correct?

**Comment by itsmeichigo** [comment]
This is true. I must have overlooked that. Sorry for the convenience, will push an update soon.

Thanks.

**Comment by nihilenz** [comment]
Thanks!
