### ISSUE TITLE
How can I fix the width per second?

### ISSUE THREAD

**Issue by harryworld** [itsmeichigo/ICGVideoTrimmer#9]
I tried to set `minLength` and `maxLength` to both 1 second, but then the trimmer between the two thumbnails becomes full width. In other words, I couldn't see the overlay views anymore?

How should I set this correctly?

Thanks

**Comment by itsmeichigo** [comment]
Are you sure you want the maxLength to be 1 second? If you play around with the sample project, you'll see that the full width of the screen equals the maximum length you set. You can swipe the view to choose the part of the video you want to trim.

What do you mean by the overlay views? Please clarify.

**Comment by harryworld** [comment]
Yes I want 1 second, and I don't want to allow the swipe.

By overlay view, it's just referring to your code `leftOverlayView` and `rightOverlayView`

**Comment by harryworld** [comment]
After studying your source code more deeply, to my understandings, you set `widthPerSecond` based on `duration` and `maxLength`, while I want it to base on a fixed width. I have modified the code to my own need. Thanks for your time.

**Comment by aiyub007** [comment]
I have the same problem so please share solution so others can use that.
